language: python
python:
  - "3.3"
env:
  - DJANGO=https://www.djangoproject.com/m/releases/1.7/Django-1.7b3.tar.gz
install:
  - pip -q install $DJANGO
  - pip -q install --upgrade -r requirements.txt
before_script:
  - cp gordio_site/settings_local_example.py gordio_site/settings_local.py
  - python manage.py syncdb --noinput
  - python manage.py migrate --noinput
  - python manage.py migrate --noinput --fake
script:
  - python manage.py test
