language: python
python:
  - "3.3"
env:
  - DJANGO=http://www.djangoproject.com/download/1.7b1/tarball/
install:
  - pip -q install $DJANGO
  - pip -q install --upgrade -r requirements.txt
before_script:
  - cp gordio_site/settings_local_example.py gordio_site/settings_local.py
  - python manage.py syncdb --noinput
  - python manage.py migrate --noinput
  - python manage.py migrate --noinput --fake
script:
  - python manage.py test
